### ISSUE TITLE
German Ducky bathtub model

### ISSUE THREAD

**Issue by Brushstroke90** [paulkim26/collab-worldtour1#43]
fix model to have animated water.

**Comment by paulkim26** [comment]
What's the context for the bathtub? The title of this issue mentions a ducky, how does the rubber duck relate to the bathtub? Where in the Germany module is the bathtub?

**Comment by Brushstroke90** [comment]
it is Wollo's souvinir that you've been discussing fixing with him in the bounties channel

**Comment by paulkim26** [comment]
Ok, I inferred this issue had a larger scope than what Wollo and I discussed because of the title (I was only asked to add water to the bathtub), so I'll do that, thanks for clarifying.

**Comment by paulkim26** [comment]
New bathtub model accepted by and provided to Wollo https://discord.com/channels/973804784148688926/1225246177113538560/1269240692597850112
